#Importação de bibliotecas e funções

In [1]:
from sklearn.svm import OneClassSVM
from sklearn.metrics import confusion_matrix
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import classification_report

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


#Experimento 5 - CTU-13 (Captura 52)

In [36]:
from sklearn.svm import OneClassSVM
from sklearn.metrics import confusion_matrix
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
early_warning_url = "cap_52_outlier_10.csv"
early_warning = pd.read_csv(early_warning_url, sep=";")
file = "10"
colunas = [file+'_kurt_total_ips_origem', 
           file+'_skw_total_ips_origem',
           file+'_coefficient_variation_total_ips_origem',
           file+'_kurt_total_ips_destino', 
           file+'_skw_total_ips_destino', 
           file+'_coefficient_variation_total_ips_destino', 
           file+'_kurt_total_pacotes',
           file+'_skw_total_pacotes',           
           file+'_coefficient_variation_total_pacotes']

df = early_warning[colunas]

label = pd.read_csv('ctulabel.csv')['maior_2']

init = 97
train = 324
end = 778
x_train = df[init:train]
x_test = df[train:end]
y_real = label[train:end]

clf = OneClassSVM(gamma='auto',kernel='poly', nu = 0.027).fit(x_train)

y_test = clf.predict(x_test)
y_test_final = [0 if i == 1 else 1 for i in y_test]
print(confusion_matrix(y_real, y_test_final))
print(classification_report(y_real, y_test_final, digits = 4))


[[348  93]
 [  5   8]]
              precision    recall  f1-score   support

           0     0.9858    0.7891    0.8766       441
           1     0.0792    0.6154    0.1404        13

    accuracy                         0.7841       454
   macro avg     0.5325    0.7023    0.5085       454
weighted avg     0.9599    0.7841    0.8555       454



In [39]:
from sklearn.svm import OneClassSVM
from sklearn.metrics import confusion_matrix
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
early_warning_url = "cap_52_outlier_10.csv"
early_warning = pd.read_csv(early_warning_url, sep=";")
file = "10"
colunas = [file+'_kurt_total_ips_origem', 
           file+'_skw_total_ips_origem',
           file+'_coefficient_variation_total_ips_origem',
           file+'_kurt_total_ips_destino', 
           file+'_skw_total_ips_destino', 
           file+'_coefficient_variation_total_ips_destino', 
           file+'_kurt_total_pacotes',
           file+'_skw_total_pacotes',           
           file+'_coefficient_variation_total_pacotes']

df = early_warning[colunas]

label = pd.read_csv('ctulabel.csv')['maior_2']

init = 97
train = 324
end = 778
x_train = df[init:train]
x_test = df[train:end]
y_real = label[train:end]

clf = OneClassSVM(gamma='auto',kernel='poly', degree=1, nu = 0.01).fit(x_train)

y_test = clf.predict(x_test)
y_test_final = [0 if i == 1 else 1 for i in y_test]
print(confusion_matrix(y_real, y_test_final))
print(classification_report(y_real, y_test_final, digits = 4))


[[353  88]
 [  5   8]]
              precision    recall  f1-score   support

           0     0.9860    0.8005    0.8836       441
           1     0.0833    0.6154    0.1468        13

    accuracy                         0.7952       454
   macro avg     0.5347    0.7079    0.5152       454
weighted avg     0.9602    0.7952    0.8625       454



In [44]:
from sklearn.svm import OneClassSVM
from sklearn.metrics import confusion_matrix
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import numpy as np
early_warning_url = "cap_52_outlier_10.csv"
early_warning = pd.read_csv(early_warning_url, sep=";")
file = "10"
colunas = [file+'_kurt_total_ips_origem', 
           file+'_skw_total_ips_origem',
           file+'_coefficient_variation_total_ips_origem',
           file+'_kurt_total_ips_destino', 
           file+'_skw_total_ips_destino', 
           file+'_coefficient_variation_total_ips_destino', 
           file+'_kurt_total_pacotes',
           file+'_skw_total_pacotes',           
           file+'_coefficient_variation_total_pacotes']

df = early_warning[colunas]

label = pd.read_csv('ctulabel.csv')['maior_2']

init = 97
train = 324
end = 778
x_train = df[init:train]
x_test = df[train:end]
y_real = label[train:end]
clf = OneClassSVM(gamma='auto',kernel='poly').fit(x_train)

for i in np.arange(0.01, 1, 0.001):
    clf = OneClassSVM(gamma='auto', degree=3, kernel='poly', nu=i).fit(x_train)
    y_test = clf.predict(x_test)
    y_test_final = [0 if i == 1 else 1 for i in y_test]
    
    acc = accuracy_score(y_real, y_test_final)
    cm = confusion_matrix(y_real, y_test_final)
    print(i, acc, cm[1][1])
    if ((float(acc) > 0.77) and (int(cm[1][1]) > 0) and (int(cm[0][1]) < 96)):
        print(cm)
        print(classification_report(y_real, y_test_final, digits = 4))

0.01 0.775330396475771 8
0.011 0.775330396475771 8
0.011999999999999999 0.775330396475771 8
0.012999999999999998 0.775330396475771 8
0.013999999999999997 0.7797356828193832 8
[[346  95]
 [  5   8]]
              precision    recall  f1-score   support

           0     0.9858    0.7846    0.8737       441
           1     0.0777    0.6154    0.1379        13

    accuracy                         0.7797       454
   macro avg     0.5317    0.7000    0.5058       454
weighted avg     0.9598    0.7797    0.8527       454

0.014999999999999996 0.7775330396475771 8
0.015999999999999993 0.775330396475771 8
0.016999999999999994 0.7709251101321586 8
0.017999999999999995 0.775330396475771 8
0.018999999999999993 0.775330396475771 8
0.01999999999999999 0.775330396475771 8
0.02099999999999999 0.775330396475771 8
0.021999999999999992 0.7731277533039648 8
0.02299999999999999 0.775330396475771 8
0.023999999999999987 0.775330396475771 8
0.024999999999999988 0.775330396475771 8
0.02599999999999999 0.77

0.21399999999999983 0.8458149779735683 0
0.21499999999999983 0.8436123348017621 0
0.21599999999999983 0.8436123348017621 0
0.21699999999999983 0.8436123348017621 0
0.21799999999999983 0.8436123348017621 0
0.21899999999999983 0.8436123348017621 0
0.21999999999999983 0.8458149779735683 0
0.22099999999999984 0.8436123348017621 0
0.22199999999999984 0.8436123348017621 0
0.22299999999999984 0.8458149779735683 0
0.22399999999999984 0.8458149779735683 0
0.22499999999999984 0.8458149779735683 0
0.2259999999999998 0.8436123348017621 0
0.2269999999999998 0.8436123348017621 0
0.22799999999999981 0.8458149779735683 0
0.22899999999999981 0.8458149779735683 0
0.22999999999999982 0.8458149779735683 0
0.23099999999999982 0.8436123348017621 0
0.23199999999999982 0.8414096916299559 0
0.23299999999999982 0.8414096916299559 0
0.23399999999999982 0.8436123348017621 0
0.23499999999999982 0.8436123348017621 0
0.23599999999999982 0.8436123348017621 0
0.23699999999999982 0.8325991189427313 0
0.2379999999999998

0.4429999999999996 0.5066079295154186 2
0.4439999999999996 0.5066079295154186 2
0.4449999999999996 0.5066079295154186 2
0.4459999999999996 0.5066079295154186 2
0.4469999999999996 0.5 2
0.4479999999999996 0.4977973568281938 2
0.4489999999999996 0.4933920704845815 2
0.4499999999999996 0.486784140969163 2
0.4509999999999996 0.486784140969163 2
0.4519999999999996 0.486784140969163 2
0.4529999999999996 0.486784140969163 2
0.4539999999999996 0.486784140969163 2
0.4549999999999996 0.486784140969163 2
0.45599999999999963 0.4889867841409692 2
0.45699999999999963 0.4889867841409692 2
0.45799999999999963 0.4889867841409692 2
0.45899999999999963 0.4889867841409692 2
0.45999999999999963 0.4889867841409692 2
0.46099999999999963 0.4889867841409692 2
0.46199999999999963 0.4889867841409692 2
0.46299999999999963 0.4845814977973568 2
0.46399999999999963 0.48237885462555063 2
0.46499999999999964 0.48237885462555063 2
0.46599999999999964 0.48237885462555063 2
0.46699999999999964 0.4801762114537445 2
0.4679

0.6659999999999995 0.4008810572687225 2
0.6669999999999995 0.4008810572687225 2
0.6679999999999995 0.4008810572687225 2
0.6689999999999995 0.4008810572687225 2
0.6699999999999995 0.4008810572687225 2
0.6709999999999995 0.4008810572687225 2
0.6719999999999995 0.4008810572687225 2
0.6729999999999995 0.40308370044052866 2
0.6739999999999995 0.40308370044052866 2
0.6749999999999995 0.4008810572687225 2
0.6759999999999995 0.4008810572687225 2
0.6769999999999995 0.4008810572687225 2
0.6779999999999995 0.4008810572687225 2
0.6789999999999995 0.4008810572687225 2
0.6799999999999995 0.4008810572687225 2
0.6809999999999995 0.4008810572687225 2
0.6819999999999995 0.4008810572687225 2
0.6829999999999994 0.4008810572687225 2
0.6839999999999994 0.4008810572687225 2
0.6849999999999994 0.4008810572687225 2
0.6859999999999994 0.4008810572687225 2
0.6869999999999994 0.4008810572687225 2
0.6879999999999994 0.3964757709251101 2
0.6889999999999994 0.3964757709251101 2
0.6899999999999994 0.3964757709251101 

0.8859999999999992 0.3568281938325991 2
0.8869999999999992 0.3568281938325991 2
0.8879999999999992 0.3568281938325991 2
0.8889999999999992 0.3568281938325991 2
0.8899999999999992 0.35462555066079293 2
0.8909999999999992 0.35462555066079293 2
0.8919999999999992 0.35462555066079293 2
0.8929999999999992 0.35462555066079293 2
0.8939999999999992 0.35462555066079293 2
0.8949999999999992 0.35462555066079293 2
0.8959999999999992 0.35462555066079293 2
0.8969999999999992 0.35462555066079293 2
0.8979999999999992 0.35462555066079293 2
0.8989999999999992 0.35462555066079293 2
0.8999999999999992 0.35462555066079293 2
0.9009999999999992 0.35462555066079293 2
0.9019999999999992 0.35462555066079293 2
0.9029999999999992 0.35462555066079293 2
0.9039999999999992 0.35462555066079293 2
0.9049999999999992 0.35462555066079293 2
0.9059999999999993 0.35462555066079293 2
0.9069999999999993 0.35462555066079293 2
0.9079999999999993 0.3524229074889868 2
0.9089999999999993 0.3524229074889868 2
0.9099999999999993 0.3